### ISSUE TITLE
Unusable with CSP directives

### ISSUE THREAD

**Issue by mrudelle** [foliojs/restructure#28]
Ref to issue devongovett/pdfkit#757

[This line](https://github.com/devongovett/restructure/blob/master/src/Pointer.coffee#L11) evaluates generated code and thus cannot be used on projects relying on CSP. (without adding the `unsafe-eval` directive)

**Comment by firien** [comment]
see PR #22

**Comment by mrudelle** [comment]
Great to see work on this issue, let's hope your work gets merged soon.

**Comment by jfoclpf** [comment]
I'd like also to stress that all my big project is not on green with Google CSP validator merely because of this issue, through [pdfmake](https://github.com/bpampuch/pdfmake/issues/1360#issuecomment-385241588).

![image](https://user-images.githubusercontent.com/3984909/39536918-5181a7d8-4e38-11e8-84d9-34e8b8cce5f4.png)

pdfmake admin refers:
> Pdfmake using pdfkit library for creating pdf files, this has a dependency on restructure library where eval is used. It can not be replaced by another library. Pdfmake can not solve this problem, it must be resolved in restructure library.
> Exists issue devongovett/restructure#28 and PR devongovett/restructure#22 in restructure. We can only wait for a new version of restructure library.

Anyway, thanks for the free library and let us wait :)

**Comment by jarrettj** [comment]
+1

**Comment by devongovett** [comment]
Should be fixed by #34. Released in v2.0.0.

**Comment by thomasazdon** [comment]
When will datatables with pdfmake include v2.0 - or is there a way to force it to use version 2.0 so that I can use native capability for PDFS that match my tables?

**Comment by blikblum** [comment]
You can try https://www.npmjs.com/package/pdfmake-lite. It does not supports IE

**Comment by liborm85** [comment]
@thomasazdon pdfmake not using v2.0 because dependency on restructure is in [fontkit](https://github.com/foliojs/fontkit) and there was no new version with restructure v2.0.

**Comment by liborm85** [comment]
Reopened.
Issue is not fixed completely: https://github.com/foliojs/restructure/blob/b9e40d26a92a3ca34c78203ddc19c6032540d76d/src/VersionedStruct.js#L9-L10

**Comment by firien** [comment]
you can look at #22. it's 3 years old, but was updated for js a few months ago.

**Comment by liborm85** [comment]
Prepared PR https://github.com/foliojs/restructure/pull/36 for fix.

**Comment by flip-it** [comment]
Thanks for fixing this! Will there be a release soon so that pdfmake can be used without the CSP `unsafe-eval`?

**Comment by firien** [comment]
@flip-it, as stated at bpampuch/pdfmake#1360 a lot of things have to happen for a new pdfmake release.

a new release of restruture is a tiny step. [fontkit](https://github.com/foliojs/fontkit) is still pinned at restructure v0.5.4. fontkits current babel (v6) implementation does not like the new es6 style of restructure 2.x.  I tried playing around with it, but ran into issues with [rollup](https://github.com/rollup/rollup), which is out of date ([v0.34.13](https://github.com/rollup/rollup/releases/tag/v0.34.13) is 3½ years old), and fontkits own creator has since authored [Parcel](https://github.com/parcel-bundler/parcel)…

**Comment by liborm85** [comment]
For compatibility with new restructure in fontkit is ready in https://github.com/foliojs/fontkit/pull/225 and https://github.com/foliojs/fontkit/pull/196.
But merge and release a new version of restructure and fontkit @devongovett has to do it.
